version: '3.3'

services:
  db:
    image: mysql:${MYSQL_VERSION}
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "${APP_PORT}:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${WORDPRESS_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DATABASE}
    volumes:
      - wordpress_data:/var/www/html

  wordpress_cli:
    depends_on:
      - db
      - wordpress
    image: wordpress:cli
    user: xfs
    command: >
      /bin/sh -c '
      sleep 30;
      wp core install --path="/var/www/html" --url="http://localhost:${APP_PORT}" --title="${APP_TITLE}" --admin_user=${APP_USER} --admin_password=${APP_PASSWORD} --admin_email=${APP_EMAIL};
      
      wp plugin install all-in-one-wp-migration;

      wp plugin activate all-in-one-wp-migration;
      '
    volumes:
      - wordpress_data:/var/www/html

volumes:
    db_data: {}
    wordpress_data: